#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
# This role will install redis

- name: "pull the redis:{{ redis.version }} image"
  shell: "docker pull redis:{{ redis.version }}"
  register: result
  until: (result.rc == 0)
  retries: "{{ docker.pull.retries }}"
  delay: "{{ docker.pull.delay }}"

- name: (re)start redis
  docker_container:
    name: redis
    image: redis:{{ redis.version }}
    state: started
    recreate: true
    restart_policy: "{{ docker.restart.policy }}"
    ports:
      - "{{ redis.port }}:6379"
    env:
      TZ: "{{ docker.timezone }}"
    command:
      /bin/sh -c
      "docker-entrypoint.sh --requirepass {{ redis.password }}"

- name: wait until redis is up and running
  shell: "docker run --link redis:redis --rm redis:{{ redis.version }} redis-cli -h redis -p 6379 -a {{ redis.password }} ping"
  register: result
  until: (result.rc == 0) and (result.stdout == 'PONG')
  retries: 12
  delay: 5
