#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
# Remove controller containers.

- name: get controller name
  set_fact:
    controller_name: "{{ name_prefix ~ host_group.index(inventory_hostname) }}"

- name: remove controller
  docker_container:
    name: "{{ controller_name }}"
    state: absent
  ignore_errors: "True"

- name: remove controller log directory
  file:
    path: "{{ whisk_logs_dir }}/{{ controller_name }}"
    state: absent
  become: "{{ logs.dir.become }}"

- name: remove controller conf directory
  file:
    path: "{{ controller.confdir }}/{{ controller_name }}"
    state: absent
  become: "{{ controller.dir.become }}"
