#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
# This role will install all necessary packages for Openwhisk.

- name: check for pip
  shell: "pip"
  register: pip_result
  ignore_errors: true

- name: install pip
  shell: "curl -k https://bootstrap.pypa.io/get-pip.py | python"
  become: true
  when: pip_result.rc != 0

- name: install requests
  pip:
    name: requests
    version: 2.10.0
  become: true

- name: install docker for python
  pip:
    name: docker
    version: 4.0.2
  become: true

- name: install httplib2
  pip:
    name: httplib2
    version: 0.9.2
  become: true
